inveniosoftware/cookiecutter-invenio-instance

- {{cookiecutter.project_shortname}}/docker-services.yml
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> docker: added kibana and DB name

- cookiecutter.json
> global: set es v6 as the default version

- {{cookiecutter.project_shortname}}/babel.ini
- {{cookiecutter.project_shortname}}/docker-services.yml
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/config.py
* Fixes some whitepsace issues with the template generation.
* Adds docstrings for missing for some configuration variables.
> global: minor style and docs fixes

- {{cookiecutter.project_shortname}}/scripts/bootstrap
* close https://github.com/inveniosoftware/cookiecutter-invenio-datamodel/issues/9
> scripts: boostrap script now use requirements.txt

- {{cookiecutter.project_shortname}}/requirements.txt
* close https://github.com/inveniosoftware/cookiecutter-invenio-datamodel/issues/8
> requirements: fix instructions

- {{cookiecutter.project_shortname}}/scripts/setup
> scripts: create only admin user

- {{cookiecutter.project_shortname}}/scripts/bootstrap
Closes https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/37
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
> scripts: unpin node-sass in bootstrap

- {{cookiecutter.project_shortname}}/scripts/setup
> scripts: no users are created by the setup script

- {{cookiecutter.project_shortname}}/scripts/setup
> scripts: clean redis cache for all databases

- {{cookiecutter.project_shortname}}/INSTALL.rst
- {{cookiecutter.project_shortname}}/docs/license.rst
> docs: fix links and license section

- .travis.yml
- {{cookiecutter.project_shortname}}/.gitignore
- {{cookiecutter.project_shortname}}/.travis.yml
- {{cookiecutter.project_shortname}}/setup.py
- {{cookiecutter.project_shortname}}/tests/e2e/conftest.py
- {{cookiecutter.project_shortname}}/tests/e2e/test_front_page.py
* closes #26.
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> tests: test front page

- {{cookiecutter.project_shortname}}/Dockerfile
* closes #54.
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> docker: fix typo in Dockerfile

- {{cookiecutter.project_shortname}}/INSTALL.rst
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> docs: fix one command

- {{cookiecutter.project_shortname}}/INSTALL.rst
- {{cookiecutter.project_shortname}}/setup.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/__init__.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/config.py
> docs: update INSTALL.rst to use scripts

- {{cookiecutter.project_shortname}}/scripts/bootstrap
- fix inveniosoftware/troubleshooting#38
- fix inveniosoftware/cookiecutter-invenio-instance#38
Signed-off-by: Igor Milhit <igor.milhit@rero.ch>
> scripts: install node package into the virtual env

- {{cookiecutter.project_shortname}}/docker-compose.full.yml
> docker: small description for docker-compose.full

- {{cookiecutter.project_shortname}}/setup.py
Addresses #60 
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
> installation: addition of Flask-DebugToolbar

- {{cookiecutter.project_shortname}}/Dockerfile
- {{cookiecutter.project_shortname}}/Dockerfile.base
- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/Pipfile.lock
- {{cookiecutter.project_shortname}}/docker-compose.full.yml
Addresses https://github.com/inveniosoftware/docker-invenio/issues/1.
Depends on https://github.com/inveniosoftware/docker-invenio/pull/6 to have `inveniosoftware/centos7-python36` available.
> docker: dockerfile base

- LICENSE
- cookiecutter.json
- {{cookiecutter.project_shortname}}/LICENSE
- {{cookiecutter.project_shortname}}/MANIFEST.in
- {{cookiecutter.project_shortname}}/misc/header.jinja2
- {{cookiecutter.project_shortname}}/misc/header.py
- {{cookiecutter.project_shortname}}/misc/header.rst
> cookiecutter: automatic year and header length

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/marshmallow/json.py
* Changing field type str to SanitizedUnicode. Closes
Closes inveniosoftware/cookiecutter-invenio-datamodel/issues/42
> schemas: changing field types

- README.rst
Addresses the second point of: https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/102
> readme: adapt to version 3.1 installation

- cookiecutter.json
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/config.py
Addresses the last point of https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/102
> config: change domains to project_site

- README.rst
Addresses the third point of https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/102
> readme: add new parameters

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/marshmallow/json.py
> marshmallow: removing unused get_id method

- .travis.yml
- {{cookiecutter.project_shortname}}/Pipfile
> installation: bump invenio development version

- {{cookiecutter.project_shortname}}/Pipfile
* Pin docutils because of this issue: https://github.com/pypa/pipenv/issues/3865
> installation: pin docutils

- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/docker/haproxy/haproxy.cfg
- {{cookiecutter.project_shortname}}/run-tests.sh
> installation: bump invenio to v3.1.1

- {{cookiecutter.project_shortname}}/docker-compose.full.yml
- {{cookiecutter.project_shortname}}/docker/nginx/conf.d/default.conf
- {{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_rest.ini
* Close #105
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> docker: expose web-api on port 5000

- {{cookiecutter.project_shortname}}/docker-services.yml
> docker-services: fix mysql db typo

- README.rst
- {{cookiecutter.project_shortname}}/tests/api/conftest.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/ext.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/marshmallow/json.py
> datamodel: include "_bucket"

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/config.py
Closes #175 
Closes #178 
Requires https://github.com/inveniosoftware/invenio/pull/3969
> Files endpoints

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/config.py
- file preview endpoint
- file download endpoint
- unblocks #173
- closes #175
> global: records-ui endpoints

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/api.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/config.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/jsonschemas/records/record-v1.0.0.json
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/marshmallow/json.py
* Adds `$schema` field
* Don't overwrite `_files` the same way as `_bucket`
* Changed pid field's JSONSchema type to `string` instead of `number`
> records: temporary solution for "system fields"

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/ext.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/indexer.py
> 174 index receiver for files

- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/tests/api/conftest.py
- {{cookiecutter.project_shortname}}/tests/api/test_api_simple_flow.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/config.py
closes #172 
depends on https://github.com/inveniosoftware/invenio-records-files/pull/89
> serializers: add record link factory

- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/config.py
> config: configure content security policy

- .travis.yml
- {{cookiecutter.project_shortname}}/tests/api/test_api_record_files.py
Closes https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/212
> tests: remove unused block of code

- .travis.yml
- {{cookiecutter.project_shortname}}/.travis.yml
- {{cookiecutter.project_shortname}}/run-tests.sh
* fix CLI arguments for isort v5
> isort: fix compatibility with isort v5

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/templates/{{cookiecutter.package_name}}/frontpage.html
> add missing closing div to frontpage.html

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/templates/semantic-ui/records/search.html
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/assets/semantic-ui/less/{{cookiecutter.package_name}}/theme.config
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/109
Closes https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/250
Closes https://github.com/inveniosoftware/invenio-theme/issues/211
Requires https://github.com/inveniosoftware/invenio-search-ui/pull/111
> search: fix template loading order

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/templates/semantic-ui/records/record.html
Closes #235 
zip 
image
pdf
not previewable content
> records: add file preview

- {{cookiecutter.project_shortname}}/scripts/bootstrap
> scripts: remove comments from script

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/assets/semantic-ui/js/{{cookiecutter.package_name}}_records/index.js
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/assets/semantic-ui/js/{{cookiecutter.package_name}}_records/search_app_customizations.js
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/templates/semantic-ui/records/search.html
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/webpack.py
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/assets/semantic-ui/less/{{cookiecutter.package_name}}/theme.less
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/assets/semantic-ui/less/{{cookiecutter.package_name}}/variables.less
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/assets/semantic-ui/templates/search/ResultsGrid.item.jsx
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/assets/semantic-ui/templates/search/ResultsList.item.jsx
- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/theme/templates/semantic-ui/{{cookiecutter.package_name}}/page.html
> styles: Adds customization example

- {{cookiecutter.project_shortname}}/{{cookiecutter.package_name}}/records/templates/semantic-ui/records/record.html
* closes https://github.com/inveniosoftware/invenio-previewer/issues/139
> previewer: Makes file preview collapsable
